// Golden regression over the committed catalog designs: re-exporting "Aurora v2" next year must
// yield the identical STL, so the EXPORT-quality geometry of each designs/*.json is pinned against
// recorded numbers. DELIBERATELY fragile — any change to the curve sampler, the surface, the cutter
// layout or the kernel shows up here as a diff. After a deliberate geometry change, regenerate with
// `UPDATE_GOLDENS=1 pnpm test` and review the golden.json diff like code.
//
// Fixtures load via readFileSync, not import: tsconfig has no resolveJsonModule, and runtime
// parsing is the point — the files must survive the same sanitizeDesign gate user imports do.
import { readFileSync, writeFileSync } from "node:fs";
import { afterAll, beforeAll, expect, test } from "vite-plus/test";
import { initCSG } from "parametric-kit/csg";
import { bbox, signedVolume } from "parametric-kit/testkit";
import { dims } from "./params.ts";
import { buildShade, EXPORT } from "./shade.ts";
import { buildFitter } from "./fitter.ts";
import { sanitizeDesign } from "./designs.ts";
import { genusOf } from "./test-probes.ts";

const CATALOG = ["catalog-empire-stagger", "catalog-twisted-star", "catalog-bell-vase"];
const DIR = new URL("../designs/", import.meta.url);
const GOLDEN_PATH = new URL("golden.json", DIR);

type Golden = {
  shadeVolume: number;
  bbox: { min: number[]; max: number[] };
  genus: number;
  holeCount: number;
  fitterVolume: number;
};

const UPDATE = !!process.env.UPDATE_GOLDENS;
const golden: Record<string, Golden> = UPDATE ? {} : JSON.parse(readFileSync(GOLDEN_PATH, "utf8"));
const regenerated: Record<string, Golden> = {};

beforeAll(async () => {
  await initCSG();
});

function measure(name: string): Golden {
  const d = sanitizeDesign(JSON.parse(readFileSync(new URL(`${name}.json`, DIR), "utf8")));
  // A null here means the ENVELOPE no longer parses — schema drift big enough to orphan the
  // whole catalog, which must fail loudly rather than quietly measuring defaults.
  expect(d).not.toBeNull();
  const shade = buildShade(d!.params, d!.curve, EXPORT);
  const b = bbox(shade);
  return {
    shadeVolume: signedVolume(shade),
    bbox: { min: [...b.min], max: [...b.max] },
    genus: genusOf(shade),
    holeCount: dims(d!.params, d!.curve).holeCount,
    fitterVolume: signedVolume(buildFitter(d!.params, d!.curve)),
  };
}

for (const name of CATALOG) {
  test(name, () => {
    const m = measure(name);
    // Invariants that hold golden or not: positively oriented solids, and every hole accounted
    // for in the topology (genus = holes + 1 covers the unperforated case too: 0 + 1).
    expect(m.shadeVolume).toBeGreaterThan(0);
    expect(m.fitterVolume).toBeGreaterThan(0);
    expect(m.genus).toBe(m.holeCount + 1);

    if (UPDATE) {
      regenerated[name] = m;
      return;
    }
    const g = golden[name];
    expect(g).toBeDefined();
    expect(m.holeCount).toBe(g.holeCount);
    expect(m.genus).toBe(g.genus);
    expect(Math.abs(m.shadeVolume - g.shadeVolume) / g.shadeVolume).toBeLessThan(1e-6);
    expect(Math.abs(m.fitterVolume - g.fitterVolume) / g.fitterVolume).toBeLessThan(1e-6);
    for (const side of ["min", "max"] as const) {
      for (let axis = 0; axis < 3; axis++) {
        expect(m.bbox[side][axis]).toBeCloseTo(g.bbox[side][axis], 4);
      }
    }
  });
}

afterAll(() => {
  if (!UPDATE) return;
  const out = {
    note: "Generated by UPDATE_GOLDENS=1 pnpm test. Regenerate only after a DELIBERATE geometry change, and review this diff like code.",
    ...regenerated,
  };
  writeFileSync(GOLDEN_PATH, `${JSON.stringify(out, null, 2)}\n`);
});
